config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :videos
  resources :sections
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/myeu', to: 'welcome#myeu'
  get 'confirm_phone', to: 'welcome#confirm_phone'
  post 'verify_otp', to: 'welcome#verify_otp'

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :section

  def youtube_id(youtube_url)
    regex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    match = regex.match(youtube_url)
    if match && !match[1].blank?
      match[1]
    else
      nil
    end
  end
  
  
    def video_embed(video_url)

    # REGEX PARA EXTRAER EL ID DEL VIDEO
    regex_id = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/|vimeo\.com\/)([a-zA-Z0-9_-]{8,11})/
    match_id = regex_id.match(video_url)
    video_id = ""
    if match_id && !match_id[1].blank?
      video_id = match_id[1]
    end

    # REGEX PARA EXTRAER EL PROVEEDOR - YOUTUBE/VIMEO
    regex_prov = /(youtube|youtu\.be|vimeo)/
    match_prov = regex_prov.match(video_url)
    video_prov = ""
    if match_prov && !match_prov[1].blank?
      video_prov = case match_prov[1]
                     when "youtube"
                       :youtube
                     when "youtu.be"
                       :youtube
                     when "vimeo"
                       :vimeo
      end
    end

    case video_prov
      when :youtube
        "https://www.youtube.com/embed/#{video_id}"
      when :vimeo
        "https://player.vimeo.com/video/#{video_id}"
    end

  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:show,:index]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
    @section_id = params[:section_id]
  end

  # GET /videos/1/edit
  def edit
    @section_id = @video.section.id
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :video_link,:minutes, :section_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="fregment-login">
    <div class="screen">
        <div class="shape">
            <%= link_to :back do %>
              <i class="fa fa-chevron-left back2"></i>
            <% end %>
            <img src="../../images/shape1.svg" alt="" class="shape1">
            <img src="../../images/shape2.svg" alt="" class="shape2">
            <div class="container">
                <div class="l-page">
                <h2 class="title ttt">Create/Edit Video</h2>

                <div class="user-input">
                    <%= form_with(model: video) do |form| %>
                      <% if video.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(video.errors.count, "error") %> prohibited this section from being saved:</h2>

                        <ul>
                          <% video.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>


                    <div class="field">
                      <%= form.text_field :title, class: 'input',placeholder: 'Video Title' %>
                    </div>

                    <div class="field">
                      <%= form.text_field :video_link, class: 'input',placeholder: 'Video Link' %>
                    </div>

                    <div class="field">
                      <%= form.text_field :minutes, class: 'input',placeholder: 'Video minutes' %>
                    </div>

                    <div class="field">
                      <%= form.hidden_field :section_id, :value => @section_id %>
                    </div>


                    <%= form.submit class: 'user-input button ' %>
                  <% end %>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/videos/edit.html.erb
<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video link</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <iframe src="<%= video.video_embed(video.video_link) %>" title="W3Schools Free Online Web Tutorials"></iframe>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.video_link %></td>
        <td><%= video.section_id %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<div class="fregment-search">
  <div class="screen">
    <div class="s-banner">
      <div>
        <%= link_to :back do %>
            <i class="fa fa-chevron-left back"></i>
        <% end %>
      </div>
        <iframe width='100%' height="400" src="<%= @video.video_embed(@video.video_link) %>" title="W3Schools Free Online Web Tutorials"></iframe>
    </div>

    <section>
        <div class="container">
                <h2 class="title tt"><%= @video.title %></h2>
                <p><%= @video.minutes %> MIN</p>
                <% if current_user.admin? %>
                  <%= link_to 'Delete Video', video_path, method: :delete, class: 'btn btn-primary pay clicked' %>
                  <%= link_to 'Edit Video', edit_video_path(@video), class: 'btn btn-primary pay clicked' %>
                <% end %>
                <%= link_to 'Back', :back, class: 'btn btn-primary pay clicked' %>
        </div>
    </section>
  </div>
</div>


<% if current_user.admin? %>
<%= link_to 'Edit', edit_video_path(@video) %>
<% end %>
<%= link_to 'Back', videos_path %>