config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :videos
  resources :sections
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/myeu', to: 'welcome#myeu'
  get 'confirm_phone', to: 'welcome#confirm_phone'
  post 'verify_otp', to: 'welcome#verify_otp'

end

app/models/section.rb
class Section < ApplicationRecord
	has_many :videos, :dependent => :destroy
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:show,:index]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<div class="fregment-login">
    <div class="screen">
        <div class="shape">
            <%= link_to :back do %>
              <i class="fa fa-chevron-left back2"></i>
            <% end %>
            <img src="../../images/shape1.svg" alt="" class="shape1">
            <img src="../../images/shape2.svg" alt="" class="shape2">
            <div class="container">
                <div class="l-page">
                <h2 class="title ttt">Create/Edit Section</h2>

                <div class="user-input">
                  <%= form_with(model: section) do |form| %>
                    <% if section.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

                        <ul>
                          <% section.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>


                    <div class="field">
                      <%= form.text_field :name, class: 'input',placeholder: 'Section Name' %>
                    </div>

                    <%= form.submit class: 'user-input button ' %>
                  <% end %>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/sections/edit.html.erb
<%= render 'form', section: @section %>

app/views/sections/index.html.erb
 <div class="fregment-course">
     <div class="screen">
         <div class="container">
             <h2 class="title tt">Gyms  <% if current_user.admin? %><%= link_to 'New Gym', new_section_path, class: 'btn btn-primary' %><% end %></h2>
             <div class="course-main">
                <% @sections.each do |section| %>
                    <%= link_to section_path(section) do %>
                    <div class="items mr card bg-dark text-white" style="border-radius: 10px; margin-bottom: 2%;">
                      <img src="images/items.png" class="card-img"  alt="...">
                      <div class="card-img-overlay">
                        <h5 class="card-title before"><%= section.name %></h5>
                        <p class="card-text after"><%= section.videos.sum(:minutes) %> MIN</p>
                      </div>
                    </div>
                    <% end %>
                <% end %>
             </div>
         </div>
     </div>
 </div>

app/views/sections/new.html.erb
<%= render 'form', section: @section %>

app/views/sections/show.html.erb
<div class="fregment-search">
  <div class="screen">
    <div class="s-banner">
        <img src="../images/s-banner.svg" width="100%" alt="">
        <%= link_to :back do %>
            <i class="fa fa-chevron-left back"></i>
        <% end %>
    </div>

    <section>
        <div class="container">
                <h2 class="title tt"><%= @section.name %></h2>
                <p ><%= @section.videos.sum(:minutes) %> MIN</p>
                <% if current_user.admin? %>
                  <%= link_to 'Add New Video', new_video_path(section_id: @section.id), class: 'btn btn-primary pay clicked' %>
                  <%= link_to 'Edit Section', edit_section_path(@section), class: 'btn btn-success pay' %>
                  <%= link_to 'Destroy', section_path(@section), method: :delete, class: 'btn btn-danger pay', data: { confirm: 'Are you sure?' }%>
                <% end %>

           <div class="video-main">
            <% i=0 %>
            <% @section.videos.each do |video| %> 
              <% i=i+1 %>
              <div class="video">
                  <h1><%= i %></h1>
                  <div class="in">
                      <p><%= video.title %></p>
                      <p class="time"><%= video.minutes %> min</p>
                  </div>
                  <%= link_to video do %>
                      <%= fa_icon 'fas fa-play-circle play' %>
                  <% end %>
              </div>
            <% end %>
         </div>
        </div>
    </section>
  </div>
</div>