config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :videos
  resources :sections
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/myeu', to: 'welcome#myeu'
  get 'confirm_phone', to: 'welcome#confirm_phone'
  post 'verify_otp', to: 'welcome#verify_otp'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		@sections = Section.all
	end

	def confirm_phone
	end

	def verify_otp
	    if session[:otp] == params[:verification_code].to_i
	      current_user.update(active: true)
	      redirect_to root_path, notice: 'User signed up successfully'
	    else
	      flash.now[:notice] = 'Invalid confirmation code!'
	      render :confirm_phone
	    end
	end
end

app/views/welcome/confirm_phone.html.erb
<div class="fregment-login">
    <div class="screen">
        <div class="shape">
            <a href="index.html"><i class="far fa-chevron-left back2"></i></a>
            <img src="../images/shape1.svg" alt="" class="shape1">
            <img src="../images/shape2.svg" alt="" class="shape2">
            <div class="container">
                <div class="l-page">
                <h2 class="title ttt">Confirm Your Phone Number</h2>

                <div class="user-input">
                  <%= form_tag('/verify_otp', method: :post) do %>
                    <%= text_field_tag 'verification_code', nil, placeholder: 'Enter Code' %>

                    <%= submit_tag "Verify", class: 'user-input button ' %>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/home.html.erb
    <div class="fregment-home active">
    <section>
        <div class="screen">
            <div class="banner">
                <div class="logo">
                <img src="../images/site-logo.png" alt="">
                </div>
                <div class="content">
                <h2>Where Enterepreneurs <br> Are Created</h2>
                <p>You Are Only One Month Away</p>
                </div>
                <center>
                    <%= link_to 'Learn More', sections_path, class: 'btn btn-primary' %>
                </center>
            </div>
        </div>
    </section>

    <section>
        <div class="screen">
            <div class="container">
                <div class="main">
                <h2 class="title">Try this</h2>

                <div class="wraper">
                    <% @sections.limit(4).each do |section| %>
                        <%= link_to section_path(section) do %>
                        <div class="items mr card bg-dark text-white" style="border-radius: 10px;">
                          <img src="images/items.png" class="card-img"  alt="...">
                          <div class="card-img-overlay">
                            <h5 class="card-title before"><%= section.name %></h5>
                            <% if section.videos != nil %>
                            <p class="card-text after"><%= section.videos.sum(:minutes) %> MIN</p>
                            <% end %>
                          </div>
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            </div>
        </div>
    </section>
    </div>

app/views/welcome/myeu.html.erb
 <div class="fregment-account">
     <div class="screen">
        <div class="container">
            <h2 class="a-title">My Deus Enterepreneur University</h2>

            <div class="acc-main">
                <p class="acc-title">ACCOUNT</p>
                <% if user_signed_in? %>
                    <div class="option logout">
                        <p align="left"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
                        <i class="far fa-chevron-right"></i>
                    </div>

                    <div class="option edit">
                        <p align="left"><%= link_to 'Edit profile', edit_user_registration_path%></p>
                        <i class="far fa-chevron-right"></i>
                    </div>

                    <div class="option">
                        <p align="left"><%= link_to 'Documents', documents_path %></p>
                        <i class="far fa-chevron-right"></i>
                    </div>
                <% else %>
                    <div class="option login">
                        <p align="left"><%= link_to 'Login', new_user_session_path %></p>
                        <i class="far fa-chevron-right"></i>
                    </div>

                    <div class="option create">
                        <p align="left"><%= link_to 'Create Account', new_user_registration_path %></p>
                        <i class="far fa-chevron-right"></i>
                    </div>
                <% end %>




                <p class="acc-title">ABOUT</p>

                <div class="option">
                    <p>Support</p>
                    <i class="far fa-chevron-right"></i>
                </div>

                <div class="option">
                    <p>Terms & Conditions</p>
                    <i class="far fa-chevron-right"></i>
                </div>

                <div class="option">
                    <p>Privacy policy</p>
                    <i class="far fa-chevron-right"></i>
                </div>
            </div>
        </div>
     </div>
 </div>