config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :videos
  resources :sections
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/myeu', to: 'welcome#myeu'
  get 'confirm_phone', to: 'welcome#confirm_phone'
  post 'verify_otp', to: 'welcome#verify_otp'

end

app/models/document.rb
class Document < ApplicationRecord
	has_one_attached :file
	validates :file, presence: true
	validates :title, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title,:file)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<div class="fregment-login">
    <div class="screen">
        <div class="shape">
            <%= link_to :back do %>
              <i class="fa fa-chevron-left back2"></i>
            <% end %>
            <img src="../../images/shape1.svg" alt="" class="shape1">
            <img src="../../images/shape2.svg" alt="" class="shape2">
            <div class="container">
                <div class="l-page">
                <h2 class="title ttt">Create Document</h2>

                <div class="user-input">
                    <%= form_with(model: document) do |form| %>
                      <% if document.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(document.errors.count, "error") %> prohibited this section from being saved:</h2>

                        <ul>
                          <% document.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>


                    <div class="field">
                      <%= form.text_field :title, class: 'input',placeholder: 'Document Title' %>
                    </div>

                    <div class="field">
                      <%= form.file_field :file, class: 'input' %>
                    </div>


                    <%= form.submit class: 'user-input button ' %>
                  <% end %>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/documents/edit.html.erb
<%= render 'form', document: @document %>

app/views/documents/index.html.erb
 <div class="fregment-account">
     <div class="screen">
        <div class="container">
            <h2 class="a-title">Documents</h2>
            <% @documents.each do |document| %>
              <div class="acc-title">
                  <p><%= document.title %>
                  <div align="right">
                  <% if document.file.attached? %>
                    <%= link_to 'Download', rails_blob_path(document.file, disposition: 'attachment'),class: 'btn btn-sm btn-info' %>
                    <% if current_user.admin? %>
                      <%= link_to 'Destroy', document, method: :delete, class: 'btn btn-danger btn-sm' , data: { confirm: 'Are you sure?' }%>
                    <% end %>
                  <% end %>
                </div>
                </p>
              </div>
            <% end %>
            </div>
            <% if current_user.admin? %>
              <div class="actions" align="center">
                <%= link_to 'New Document', new_document_path, class: 'btn btn-info' %>
              </div>
            <% end %>
        </div>
     </div>
 </div>

app/views/documents/new.html.erb
<%= render 'form', document: @document %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>